image_finetune: false

output_dir: "EXP"
pretrained_model_path: "runwayml/stable-diffusion-v1-5"

unet_additional_kwargs:
  use_motion_module              : true
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : false
  unet_use_temporal_attention    : false

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : true
    temporal_position_encoding_max_len : 24
    temporal_attention_dim_div         : 1
    zero_initialize                    : true

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

train_data:
  sample_size:     224
  sample_stride:   4
  sample_n_frames: 6

val_config:
  num_inference_steps: 20
  guidance_scale:  12.5


trainable_modules:
  - "attn1"
  - "attn2"
  - "motion_modules"

unet_checkpoint_path: ""

learning_rate: 1e-3
lr_scheduler: "polynomial"
lr_warmup_steps: 50
train_batch_size: 2


num_train_epochs:      50
#brain_model_train_epoch: 30
checkpointing_epochs: -1
checkpointing_steps: 60
gradient_accumulation_steps: 1


validation_steps:       5000
validation_steps_tuple: [2, 50]

global_seed: 42
mixed_precision_training: true

is_debug: False


n_prompt: "semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck"